import { Ambulance, Materiel } from '../../types';


export const ambulancesData: Ambulance[] = [
  {
    id: "AMB-101",
    type: "Ambulance",
    modele: "Mercedes Sprinter 316",
    immatriculation: "AA-123-BB",
    status: "En service",
    localisation: "Centre-ville",
    maintenanceStatus: "À jour",
    dateDernierEntretien: "15/01/2025",
    prochainEntretien: "15/04/2025",
    kilometrage: 24560,
    prochaineRevision: "30000 km",
    carburant: "Diesel",
    notes: "Pneus à vérifier lors du prochain entretien",
    ct: "21 Novembre 2025",
    disponibilite: "Disponible",
    pneus: "Bon état",
    freins: "Usure modérée",
    derniereVidange: "20 Janvier 2025",
    courroieDistribution: "À vérifier dans 10 000 km",
  },
  {
    id: "AMB-203",
    type: "Ambulance",
    modele: "Renault Master III",
    immatriculation: "CC-456-DD",
    status: "En service",
    localisation: "Hôpital Saint-Pierre",
    maintenanceStatus: "À jour",
    dateDernierEntretien: "03/02/2025",
    prochainEntretien: "03/05/2025",
    kilometrage: 18790,
    prochaineRevision: "20000 km",
    carburant: "Diesel",
    notes: "RAS",
    ct: "30 Septembre 2025",
    disponibilite: "Disponible",
    pneus: "Neufs",
    freins: "Remplacés récemment",
    derniereVidange: "10 Février 2025",
    courroieDistribution: "Bonne condition",
  },
  {
    id: "VSL-301",
    type: "VSL",
    modele: "Volkswagen Passat",
    immatriculation: "EE-789-FF",
    status: "En service",
    localisation: "Clinique des Lilas",
    maintenanceStatus: "Vérification nécessaire",
    dateDernierEntretien: "10/12/2024",
    prochainEntretien: "10/03/2025",
    kilometrage: 32450,
    prochaineRevision: "35000 km",
    carburant: "Diesel",
    notes: "Bruit suspect au niveau de la transmission",
    ct: "15 Juin 2025",
    disponibilite: "Disponible",
    pneus: "Usure modérée",
    freins: "Bon état",
    derniereVidange: "05 Décembre 2024",
    courroieDistribution: "À vérifier",
  },
  {
    id: "AMB-417",
    type: "Ambulance",
    modele: "Fiat Ducato",
    immatriculation: "GG-012-HH",
    status: "Hors service",
    localisation: "Garage de maintenance",
    maintenanceStatus: "Réparation en cours",
    dateDernierEntretien: "22/01/2025",
    prochainEntretien: "22/04/2025",
    kilometrage: 42000,
    prochaineRevision: "45000 km",
    carburant: "Diesel",
    notes: "Remplacement du système de freinage",
    ct: "10 Mars 2025",
    disponibilite: "Indisponible",
    pneus: "À changer",
    freins: "En cours de remplacement",
    derniereVidange: "15 Janvier 2025",
    courroieDistribution: "Bonne condition",
  },
  {
    id: "VSL-420",
    type: "VSL",
    modele: "Citroën C5",
    immatriculation: "II-345-JJ",
    status: "Hors service",
    localisation: "Station 2",
    maintenanceStatus: "Contrôle technique dépassé",
    dateDernierEntretien: "05/11/2024",
    prochainEntretien: "05/02/2025",
    kilometrage: 28760,
    prochaineRevision: "30000 km",
    carburant: "Diesel",
    notes: "CT à reprogrammer d'urgence",
    ct: "Dépassé",
    disponibilite: "Indisponible",
    pneus: "Bon état",
    freins: "Usure normale",
    derniereVidange: "20 Octobre 2024",
    courroieDistribution: "À surveiller",
  },
  {
    id: "AMB-118",
    type: "Ambulance",
    modele: "Mercedes Sprinter 316",
    immatriculation: "KK-678-LL",
    status: "Hors service",
    localisation: "Station 1",
    maintenanceStatus: "Réparation en cours",
    dateDernierEntretien: "18/12/2024",
    prochainEntretien: "18/03/2025",
    kilometrage: 36890,
    prochaineRevision: "40000 km",
    carburant: "Diesel",
    notes: "Panne électrique du système d'oxygène",
    ct: "25 Avril 2025",
    disponibilite: "Indisponible",
    pneus: "Bon état",
    freins: "Bon état",
    derniereVidange: "10 Décembre 2024",
    courroieDistribution: "Récemment changée",
  },
  {
    id: "VSL-555",
    type: "VSL",
    modele: "Renault Talisman",
    immatriculation: "MM-901-NN",
    status: "En service",
    localisation: "Hôpital Necker",
    maintenanceStatus: "Entretien imminent",
    dateDernierEntretien: "02/03/2025",
    prochainEntretien: "02/06/2025",
    kilometrage: 14850,
    prochaineRevision: "15000 km",
    carburant: "Diesel",
    notes: "Prévoir changement filtres",
    ct: "12 Août 2025",
    disponibilite: "Disponible",
    pneus: "Bon état",
    freins: "Usure légère",
    derniereVidange: "25 Février 2025",
    courroieDistribution: "Bonne condition",
  },
  {
    id: "AMB-777",
    type: "Ambulance",
    modele: "Volkswagen Crafter",
    immatriculation: "OO-234-PP",
    status: "En service",
    localisation: "Aéroport CDG",
    maintenanceStatus: "À jour",
    dateDernierEntretien: "25/02/2025",
    prochainEntretien: "25/05/2025",
    kilometrage: 19750,
    prochaineRevision: "20000 km",
    carburant: "Diesel",
    notes: "Révision du matériel médical effectuée",
    ct: "18 Juillet 2025",
    disponibilite: "Disponible",
    pneus: "Neufs",
    freins: "Neufs",
    derniereVidange: "20 Février 2025",
    courroieDistribution: "Excellente condition",
  },
  {
    id: "AMB-505",
    type: "Ambulance",
    modele: "Ford Transit",
    immatriculation: "QQ-567-RR",
    status: "Hors service",
    localisation: "Caserne des pompiers",
    maintenanceStatus: "Contrôle nécessaire",
    dateDernierEntretien: "30/11/2024",
    prochainEntretien: "28/02/2025",
    kilometrage: 45620,
    prochaineRevision: "50000 km",
    carburant: "Diesel",
    notes: "Problème de démarrage à froid",
    ct: "05 Mai 2025",
    disponibilite: "Indisponible",
    pneus: "Usure avancée",
    freins: "À vérifier",
    derniereVidange: "15 Novembre 2024",
    courroieDistribution: "À changer bientôt",
  },
  {
    id: "AMB-606",
    type: "Ambulance",
    modele: "Mercedes Sprinter 319",
    immatriculation: "SS-890-TT",
    status: "En service",
    localisation: "Champs-Élysées",
    maintenanceStatus: "À jour",
    dateDernierEntretien: "10/02/2025",
    prochainEntretien: "10/05/2025",
    kilometrage: 22340,
    prochaineRevision: "25000 km",
    carburant: "Diesel",
    notes: "Vérifier usure des plaquettes de frein",
    ct: "22 Octobre 2025",
    disponibilite: "Disponible",
    pneus: "Bon état",
    freins: "Usure modérée",
    derniereVidange: "05 Février 2025",
    courroieDistribution: "À vérifier dans 5 000 km",
  },
  {
    id: "AMB-808",
    type: "Ambulance",
    modele: "Peugeot Boxer",
    immatriculation: "UU-123-VV",
    status: "En service",
    localisation: "Gare du Nord",
    maintenanceStatus: "À jour",
    dateDernierEntretien: "01/03/2025",
    prochainEntretien: "01/06/2025",
    kilometrage: 17500,
    prochaineRevision: "20000 km",
    carburant: "Diesel",
    notes: "Véhicule récemment mis en service",
    ct: "15 Décembre 2025",
    disponibilite: "Disponible",
    pneus: "Neufs",
    freins: "Neufs",
    derniereVidange: "25 Février 2025",
    courroieDistribution: "Excellente condition",
  },
  {
    id: "VSL-909",
    type: "VSL",
    modele: "Toyota Corolla",
    immatriculation: "WW-456-XX",
    status: "En service",
    localisation: "Hôpital Bichat",
    maintenanceStatus: "Entretien imminent",
    dateDernierEntretien: "20/02/2025",
    prochainEntretien: "20/05/2025",
    kilometrage: 26500,
    prochaineRevision: "30000 km",
    carburant: "Hybride",
    notes: "Vérifier niveau d'huile moteur",
    ct: "30 Juin 2025",
    disponibilite: "Disponible",
    pneus: "Bon état",
    freins: "Usure légère",
    derniereVidange: "15 Février 2025",
    courroieDistribution: "À surveiller",
  },
  {
    id: "AMB-999",
    type: "Ambulance",
    modele: "Iveco Daily",
    immatriculation: "YY-789-ZZ",
    status: "Hors service",
    localisation: "Dépôt central",
    maintenanceStatus: "Réparation en cours",
    dateDernierEntretien: "10/01/2025",
    prochainEntretien: "10/04/2025",
    kilometrage: 51000,
    prochaineRevision: "55000 km",
    carburant: "Diesel",
    notes: "Problème de suspension arrière",
    ct: "20 Février 2025",
    disponibilite: "Indisponible",
    pneus: "Usure avancée",
    freins: "Bon état",
    derniereVidange: "05 Janvier 2025",
    courroieDistribution: "À changer",
  },
];

export const materielAmbulance: Materiel[] = [
  { id: 1, nom: "Oxygène médical", datePeremption: "" },
  { id: 2, nom: "Insufflateur manuel (BAVU)", datePeremption: "" },
  { id: 3, nom: "Masques à oxygène (adultes et enfants)", datePeremption: "" },
  { id: 4, nom: "Canules de Guedel", datePeremption: "" },
  { id: 5, nom: "Pansements stériles", datePeremption: "" },
  { id: 6, nom: "Bandes élastiques", datePeremption: "" },
  { id: 7, nom: "Compresses de gaze stériles", datePeremption: "" },
  { id: 8, nom: "Pansements stériles absorbants", datePeremption: "" },
  { id: 9, nom: "Solution antiseptique", datePeremption: "" },
  { id: 10, nom: "Gants chirurgicaux stériles", datePeremption: "" },
  { id: 11, nom: "Gants non stériles à usage unique", datePeremption: "" },
  { id: 12, nom: "Masques de protection respiratoire FFP2", datePeremption: "" },
  { id: 13, nom: "Piles/batteries pour équipements médicaux", datePeremption: "" },
  { id: 14, nom: "Électrodes pour défibrillateur", datePeremption: "" },
];

export const materielVSL: Materiel[] = [
  { id: 1, nom: "Pansements stériles absorbants (20 x 40 cm)", datePeremption: "" },
  { id: 2, nom: "Ruban adhésif parapharmaceutique (2 cm)", datePeremption: "" },
  { id: 3, nom: "Pansements adhésifs assortis", datePeremption: "" },
  { id: 4, nom: "Bandes extensibles (3 m x 10 cm)", datePeremption: "" },
  { id: 5, nom: "Compresses stériles (7,5 cm x 7,5 cm)", datePeremption: "" },
  { id: 6, nom: "Solution antiseptique", datePeremption: "" },
  { id: 7, nom: "Gants chirurgicaux stériles", datePeremption: "" },
  { id: 8, nom: "Gants non stériles à usage unique", datePeremption: "" },
  { id: 9, nom: "Masques de protection respiratoire FFP2", datePeremption: "" },
];